"""Sprint 5b/6 — BuilderSession: N tool calls → CodeDelta or BuilderFailure."""

from __future__ import annotations

import shutil
from dataclasses import dataclass, field
from typing import Callable, List, Optional, Union

from contract_registry import BuilderFailure, CodeDelta, TaskNode
from execution.adapter import ExecutionAdapter, ToolCall, ToolCallStatus, ToolResult
from execution.router import select_backend
from failure_classifier import FailureClassifier

NodeResult = Union[CodeDelta, BuilderFailure]


@dataclass
class BuilderToolPlan:
    """Planned tool calls for a single builder node (from LLM or spec)."""
    calls: List[ToolCall] = field(default_factory=list)


class BuilderSession:
    """
    One Dyson node → many tool calls → one CodeDelta or BuilderFailure.

    LLM integration (RoleEngine) dispatches tool plans; this session executes them.
    """

    def __init__(
        self,
        backend: Optional[ExecutionAdapter] = None,
        workspace_root: str = ".",
        on_tool_result: Optional[Callable[[ToolCall, ToolResult], None]] = None,
    ) -> None:
        self.workspace_root = workspace_root
        self._backend = backend
        self._on_tool_result = on_tool_result
        self._classifier = FailureClassifier()
        self._files_changed: List[str] = []
        self._diffs: List[str] = []

    def run(
        self,
        node: TaskNode,
        plan: BuilderToolPlan,
        *,
        pii_hold: bool = False,
    ) -> NodeResult:
        use_mock = self._backend is None and shutil.which("kore-exec") is None
        backend = self._backend or select_backend(
            node,
            pii_hold=pii_hold,
            workspace_root=self.workspace_root,
            use_mock=use_mock,
        )

        for call in plan.calls:
            call.node_id = node.id
            call.role = node.role
            call.workspace_root = self.workspace_root

            result = backend.execute(call)
            if self._on_tool_result:
                self._on_tool_result(call, result)

            failure = self._handle_result(backend, call, result)
            if failure is not None:
                return failure

            if call.tool in ("write_file", "edit_file") and result.status == ToolCallStatus.OK:
                path = call.args.get("path", "")
                if path and path not in self._files_changed:
                    self._files_changed.append(path)

        if not self._files_changed:
            return self._classifier.classify_tool_failure(
                ToolCall(
                    tool="builder",
                    args={},
                    node_id=node.id,
                    role=node.role,
                    workspace_root=self.workspace_root,
                ),
                "builder produced no file changes",
            )

        return CodeDelta(
            node_id=node.id,
            files_changed=list(self._files_changed),
            diff="\n".join(self._diffs),
            test_commands=[],
            confidence=0.8,
        )

    def _handle_result(
        self,
        backend: ExecutionAdapter,
        call: ToolCall,
        result: ToolResult,
    ) -> Optional[BuilderFailure]:
        if result.status == ToolCallStatus.OK:
            return None

        error = result.error or f"{call.tool} failed"
        if result.status == ToolCallStatus.FATAL:
            note = backend.on_fatal(call, result)
            constraint, _ = self._classifier.classify_tool_call(call, error)
            return BuilderFailure(note=note, constraint=constraint)

        return self._classifier.classify_tool_failure(call, error)

    @staticmethod
    def plan_from_node(node: TaskNode, workspace_root: str = ".") -> BuilderToolPlan:
        """
        Minimal plan extractor until LLM tool-calling is wired.
        Parses node.title for write targets:
          - 'write path/to/file.py' → write_file at that path
          - 'auth', 'api', 'db' (module names) → write_file <name>.py
        """
        calls: List[ToolCall] = []
        title = node.title.strip()

        if title.lower().startswith("write "):
            path = title[6:].strip()
            calls.append(ToolCall(
                tool="write_file",
                args={
                    "path": path,
                    "content": f"# {node.title}\n# Generated by KORE builder — replace with real implementation\n",
                },
                node_id=node.id,
                role=node.role,
                workspace_root=workspace_root,
            ))
        elif title and not any(ch in title for ch in ('/', '\\', '\n', '\r')):
            safe_name = title.split()[0].strip().rstrip('.')
            if safe_name:
                path = f"{safe_name}.py" if not safe_name.endswith('.py') else safe_name
                calls.append(ToolCall(
                    tool="write_file",
                    args={
                        "path": path,
                        "content": (
                            f"# {node.title}\n"
                            f"# Generated by KORE builder — replace with real implementation\n"
                            f"# Node: {node.id}  Risk: {node.risk_score}\n\n"
                        ),
                    },
                    node_id=node.id,
                    role=node.role,
                    workspace_root=workspace_root,
                ))

        return BuilderToolPlan(calls=calls)
